export const politicalTopics = [
	'economy',
	'foreign policy',
	'health care',
	'environment',
	'energy',
	'education',
	'digital infrastructure',
	'social welfare',
	'labor',
	'justice system',
	'financial system',
	'agriculture',
	'housing',
	'science and technology',
	'arts and culture',
	'religion',
	'family and children',
	'animal rights',
	'drug policy',
	'foreign aid',
	'human rights',
	'immigration',
	'national security',
	'public safety',
	'trade',
	'privacy',
	'reproductive rights',
	'taxation',
	'free speech',
	'disability rights',
	'surveillance',
	'internet freedom',
	'climate change',
	'mental health',
	'urban development',
	'space exploration',
	'cybersecurity',
	'public transportation',
	'renewable energy',
	'food security',
	'gender equality',
	'racial equality',
	'elderly care',
	'youth programs',
	'tourism',
	'wildlife conservation',
	'ocean conservation',
	'direct democracy',
].toSorted()

export const maxTopics = 5

export const storageKey = 'selectedTopics'
